apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  labels:
    app: nodejs-project
spec:
  selector:
    app: nodejs-project
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31200
